import type { ComponentType } from "react";
import { Boxes, Droplets, Layers, Paintbrush, Shield, Sparkles, Wrench } from "lucide-react";

export type Brand = "sika" | "terraco" | "lafarge";
export type ProductCategory = "Tile Adhesive" | "Retail" | "Specialists";

export type Product = {
  id: string;
  brand: Brand;
  name: string;
  category: ProductCategory;
  description: string;
  unit: string;
  formats: string[];
  colors?: string[];
  image: string;
  imageNote?: string;
  technicalSheet: string;
  sourceUrl: string;
  highlights: string[];
  specifications: { label: string; value: string }[];
  badge?: string;
  featured?: boolean;
};

export type BrandProfile = {
  name: string;
  color: string;
  accent: string;
  dark: string;
  tagline: string;
  description: string;
  mood: string;
  heroImage: string;
  icon: ComponentType<{ className?: string }>;
};

export const BRANDS: Record<Brand, BrandProfile> = {
  sika: {
    name: "Sika",
    color: "#D8282F",
    accent: "#F5B325",
    dark: "#381411",
    tagline: "Building Trust depuis plus d'un siecle.",
    description: "Chimie de construction, etancheite, collage, scellement et protection du beton.",
    mood: "Rouge chantier, jaune signaletique et cartes techniques tres directes.",
    heroImage: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1600&q=80",
    icon: Shield,
  },
  terraco: {
    name: "Terraco",
    color: "#0A35A5",
    accent: "#2F6DFF",
    dark: "#071B5C",
    tagline: "Finitions scandinaves pour facades et interieurs.",
    description: "Enduits decoratifs, facades, ETICS, coatings et solutions de finition eco-responsables.",
    mood: "Bleu technique, lignes franches et presentation corporate.",
    heroImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80",
    icon: Paintbrush,
  },
  lafarge: {
    name: "Lafarge",
    color: "#16A34A",
    accent: "#111111",
    dark: "#0F1F19",
    tagline: "Ciments, betons et granulats pour ouvrages solides.",
    description: "Solutions cimentaires, mortiers et materiaux lourds pour chantiers structurants.",
    mood: "Vert industriel, noir graphique, blocs robustes et donnees lisibles.",
    heroImage: "https://images.unsplash.com/photo-1517089596392-fb9a9033e05b?auto=format&fit=crop&w=1600&q=80",
    icon: Layers,
  },
};

const sikaFallback = "/naf.github.io/brands/sika.png";
const unavailablePhoto = "Photo officielle du conditionnement non publiee sur la page Sika Algerie.";
const spec = (conditionnement: string, usage: string) => [
  { label: "Conditionnement", value: conditionnement },
  { label: "Usage principal", value: usage },
  { label: "Marque", value: "Sika" },
];

export const PRODUCTS: Product[] = [
  {
    id: "sikaceram-511",
    brand: "sika",
    name: "SikaCeram-511",
    category: "Tile Adhesive",
    description: "Mortier-colle cimentaire pour la pose de carreaux en interieur et en exterieur.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hfe/hbd/8995587555358/511-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/d/sikaceram_-511.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/colles-a-carreaux/sikaceram-511.html",
    highlights: ["Colle carrelage a base ciment", "Application murs et sols", "Usage interieur et exterieur"],
    specifications: spec("Sac de 25 kg", "Pose de carreaux"),
    badge: "Carrelage",
    featured: true,
  },
  {
    id: "sikaceram-522",
    brand: "sika",
    name: "SikaCeram-522",
    category: "Tile Adhesive",
    description: "Mortier-colle ameliore pour carreaux ceramiques, adapte aux travaux de pose exigeants.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/he5/hc8/8995587457054/522-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/e/sikaceram_-522.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/colles-a-carreaux/sikaceram-522.html",
    highlights: ["Adherence amelioree", "Application murs et sols", "Pose professionnelle"],
    specifications: spec("Sac de 25 kg", "Pose de carreaux"),
    featured: true,
  },
  {
    id: "sikaceram-255-starflex",
    brand: "sika",
    name: "SikaCeram-255 StarFlex",
    category: "Tile Adhesive",
    description: "Mortier-colle flexible haute performance pour la pose de carrelage sur supports exigeants.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/a/sikaceram_-255_starflexdz.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/colles-a-carreaux.html",
    highlights: ["Formule flexible", "Pose technique de carrelage", "Haute performance"],
    specifications: spec("Sac de 25 kg", "Pose flexible de carreaux"),
    badge: "Flexible",
    featured: true,
  },
  {
    id: "sikaceram-510-joint",
    brand: "sika",
    name: "SikaCeram-510 Joint",
    category: "Tile Adhesive",
    description: "Mortier de jointoiement pour carreaux, propose dans une palette de couleurs pour les finitions.",
    unit: "Sac 5 kg",
    formats: ["5 kg"],
    colors: ["Blanc", "Noir", "Gris clair", "Gris fonce", "Creme", "Chocolat", "Sable", "Sahara"],
    image: "https://pim2.sika.com/medias/sys_master/root/h1b/he6/8997459656734/sika-510-joint.png",
    technicalSheet: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/mortier-pour-joints/sikaceram-510-joint.html",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/mortier-pour-joints/sikaceram-510-joint.html",
    highlights: ["Jointoiement de carreaux", "Finition coloree", "Large choix de teintes"],
    specifications: spec("Sac de 5 kg", "Joints de carrelage"),
  },
  {
    id: "sikawall-10-primer",
    brand: "sika",
    name: "SikaWall-10 Primer",
    category: "Tile Adhesive",
    description: "Primaire d'accrochage pour la preparation des supports avant application des systemes muraux.",
    unit: "Bidon 20 kg",
    formats: ["20 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/h62/h08/8995587325982/Sikawall10primer-3-.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/1/sikawall_-10-primer.pdf",
    sourceUrl: "https://dza.sika.com/fr/products/sikawall-10-primer.html",
    highlights: ["Preparation du support", "Primaire d'accrochage", "Application murale"],
    specifications: spec("Bidon de 20 kg", "Primaire pour supports muraux"),
  },
  {
    id: "conservado-naturiales",
    brand: "sika",
    name: "Conservado Naturiales",
    category: "Tile Adhesive",
    description: "Solution de protection pour surfaces minerales, destinee aux travaux de conservation et de finition.",
    unit: "Bidon 10 L",
    formats: ["10 L"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/4/conservado_naturiales.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/revetements-des-mursetfacades/conservado-naturiales.html",
    highlights: ["Protection des surfaces", "Application de finition", "Conditionnement professionnel"],
    specifications: spec("Bidon de 10 L", "Protection de surfaces minerales"),
  },
  {
    id: "sikatop-130-flex",
    brand: "sika",
    name: "SikaTop-130 Flex",
    category: "Tile Adhesive",
    description: "Mortier d'impermeabilisation flexible bi-composant pour ouvrages et supports cimentaires.",
    unit: "Kit 32 kg",
    formats: ["Sac 24 kg + bidon 8 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hb3/h0f/8995425517598/130-Vue-active.png",
    technicalSheet: "https://dza.sika.com/fr/construction/systemes-d-etancheite/revetements-d-impermeabilisation-a-base-de-ciment/sikatop-130-flex.html",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/revetements-d-impermeabilisation-a-base-de-ciment/sikatop-130-flex.html",
    highlights: ["Systeme bi-composant", "Etancheite flexible", "Kit pret a melanger"],
    specifications: spec("Sac de 24 kg + bidon de 8 kg", "Impermeabilisation flexible"),
    featured: true,
  },
  {
    id: "hydrofuge-sika-liquide",
    brand: "sika",
    name: "Hydrofuge Sika Liquide",
    category: "Retail",
    description: "Adjuvant liquide d'impermeabilisation pour mortiers et betons, destine a limiter la penetration d'eau.",
    unit: "Bidon 2 / 5 / 10 kg",
    formats: ["2 kg", "5 kg", "10 kg"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/2/hydrofuge_sika_liquide.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/adjuvants-d-impermeabilisationpourbeton/hydrofuge-sika-liquide.html",
    highlights: ["Hydrofugation des mortiers", "Reduction de la penetration d'eau", "Trois formats disponibles"],
    specifications: spec("Bidons de 2 kg, 5 kg et 10 kg", "Impermeabilisation de mortiers et betons"),
    featured: true,
  },
  {
    id: "sikalatex-pro",
    brand: "sika",
    name: "SikaLatex Pro",
    category: "Retail",
    description: "Resine d'accrochage et d'amelioration des mortiers pour reprises, chapes et enduits.",
    unit: "Bidon 2 / 5 / 10 kg",
    formats: ["2 kg", "5 kg", "10 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/h37/h1b/8995705946142/LATEX-PRO-Vue-active-1-.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/7/sika_latex_pro.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sikalatex-pro.html",
    highlights: ["Resine d'accrochage", "Ameliore les mortiers", "Trois formats disponibles"],
    specifications: spec("Bidons de 2 kg, 5 kg et 10 kg", "Accrochage et amelioration des mortiers"),
    badge: "Polyvalent",
    featured: true,
  },
  {
    id: "sikalatex-310-rtu",
    brand: "sika",
    name: "SikaLatex-310 RTU",
    category: "Retail",
    description: "Primaire d'adherence pret a l'emploi pour reprises de beton et travaux de reparation.",
    unit: "Bidon 5 kg",
    formats: ["5 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hd8/h49/8995706044446/3d-310-5kg.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/2/sikalatex_-310-rtu.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sikalatex-310-rtu.html",
    highlights: ["Pret a l'emploi", "Primaire d'adherence", "Reprises de beton"],
    specifications: spec("Bidon de 5 kg", "Primaire d'adherence"),
  },
  {
    id: "sika-plastocrete-160a",
    brand: "sika",
    name: "Sika Plastocrete-160 A",
    category: "Retail",
    description: "Plastifiant pour beton permettant d'ameliorer l'ouvrabilite et la mise en oeuvre.",
    unit: "Bidon 5 kg",
    formats: ["5 kg"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/w/sika_plastocrete_-160a.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/adjuvants-pour-beton/beton-pret-a-l-emploi/plastifiants/sika-plastocrete-160a.html",
    highlights: ["Plastifiant pour beton", "Ameliore l'ouvrabilite", "Mise en oeuvre facilitee"],
    specifications: spec("Bidon de 5 kg", "Plastification du beton"),
  },
  {
    id: "sikaplast-bv-40-plus",
    brand: "sika",
    name: "SikaPlast BV-40 Plus",
    category: "Retail",
    description: "Reducteur d'eau pour beton permettant d'optimiser la maniabilite et les performances du melange.",
    unit: "Bidon 5 kg",
    formats: ["5 kg"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/q/sika_plast_-bv-40plus.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/adjuvants-pour-beton/beton-pret-a-l-emploi/reducteurs-d-eau/reducteurs-d-eau/sikaplast-bv-40-plus.html",
    highlights: ["Reducteur d'eau", "Optimise la maniabilite", "Adjuvant pour beton"],
    specifications: spec("Bidon de 5 kg", "Reduction d'eau pour beton"),
  },
  {
    id: "super-sikalite",
    brand: "sika",
    name: "Super Sikalite",
    category: "Retail",
    description: "Poudre d'impermeabilisation pour mortiers, adaptee aux petits travaux et reparations courantes.",
    unit: "Sac 1 kg",
    formats: ["1 kg"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/fr/construction/systemes-d-etancheite/poudre-d-impermeabilisationpourmortier/super-sikalite.html",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/poudre-d-impermeabilisationpourmortier/super-sikalite.html",
    highlights: ["Impermeabilisation des mortiers", "Format pratique", "Travaux courants"],
    specifications: spec("Sac de 1 kg", "Impermeabilisation de mortiers"),
  },
  {
    id: "sikafill",
    brand: "sika",
    name: "Sikafill",
    category: "Retail",
    description: "Revetement liquide d'etancheite pour toitures, disponible en blanc et rouge brique.",
    unit: "Bidon 5 / 20 kg",
    formats: ["5 kg", "20 kg"],
    colors: ["Blanc", "Rouge brique"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/fr/construction/systemes-d-etancheite/etancheite-liquide/toitures/sikafill.html",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/etancheite-liquide/toitures/sikafill.html",
    highlights: ["Etancheite liquide", "Application toiture", "Deux couleurs disponibles"],
    specifications: spec("Bidons de 5 kg et 20 kg", "Etancheite liquide de toitures"),
  },
  {
    id: "sikaflex-pro-11-fc",
    brand: "sika",
    name: "Sikaflex Pro-11 FC",
    category: "Retail",
    description: "Mastic-colle elastique polyvalent en cartouche pour collage et jointoiement dans le batiment.",
    unit: "Cartouche",
    formats: ["Cartouche"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/fr/construction/traitement-des-joints/joints-de-facades/sikaflex-pro-11-fc.html",
    sourceUrl: "https://dza.sika.com/fr/construction/traitement-des-joints/joints-de-facades/sikaflex-pro-11-fc.html",
    highlights: ["Mastic-colle polyvalent", "Application en cartouche", "Collage et joints elastiques"],
    specifications: spec("Cartouche", "Collage et jointoiement"),
    badge: "Mastic-colle",
  },
  {
    id: "sikatop-209-reservoir",
    brand: "sika",
    name: "SikaTop-209 Reservoir",
    category: "Specialists",
    description: "Mortier bi-composant d'impermeabilisation pour ouvrages hydrauliques et reservoirs.",
    unit: "Kit 30 kg",
    formats: ["Sac 20 kg + bidon 10 kg"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/8/sikatop_-209-reservoir.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/revetements-d-impermeabilisation-a-base-de-ciment/sikatop-209-reservoir.html",
    highlights: ["Systeme bi-composant", "Protection des reservoirs", "Impermeabilisation cimentaire"],
    specifications: spec("Sac de 20 kg + bidon de 10 kg", "Impermeabilisation de reservoirs"),
    featured: true,
  },
  {
    id: "sikatop-107-seal",
    brand: "sika",
    name: "SikaTop-107 Seal",
    category: "Specialists",
    description: "Mortier d'impermeabilisation bi-composant pour la protection des ouvrages en beton.",
    unit: "Kit 25 kg",
    formats: ["Sac 20 kg + bidon 5 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/h9e/h4f/8995537092638/107-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/a/sikatop_-107-sealdz.pdf",
    sourceUrl: "https://dza.sika.com/fr/products/sikatop-107-sealwp.html",
    highlights: ["Kit bi-composant", "Protection du beton", "Impermeabilisation cimentaire"],
    specifications: spec("Sac de 20 kg + bidon de 5 kg", "Impermeabilisation des ouvrages en beton"),
    featured: true,
  },
  {
    id: "sika-monotop-4012",
    brand: "sika",
    name: "Sika MonoTop-4012",
    category: "Specialists",
    description: "Mortier de reparation structurelle du beton pour travaux professionnels.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hf6/h4e/8990283595806/4012-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/a/sika_monotop_-4012.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sika-monotop-4012.html",
    highlights: ["Reparation structurelle", "Application professionnelle", "Support beton"],
    specifications: spec("Sac de 25 kg", "Reparation structurelle du beton"),
    featured: true,
  },
  {
    id: "sika-monotop-650",
    brand: "sika",
    name: "Sika MonoTop-650",
    category: "Specialists",
    description: "Mortier de reparation du beton pour remise en etat des surfaces et ouvrages.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/w/sika_monotop_-650.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sika-monotop-650.html",
    highlights: ["Mortier de reparation", "Application sur beton", "Conditionnement chantier"],
    specifications: spec("Sac de 25 kg", "Reparation du beton"),
  },
  {
    id: "sika-monotop-sf-126",
    brand: "sika",
    name: "Sika MonoTop SF-126",
    category: "Specialists",
    description: "Mortier technique pour la reparation et la protection des ouvrages en beton.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/h36/h11/8990288904222/sf126-Vue-active-1-.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/6/sika_monotop_sf-126.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sika-monotop-sf-126.html",
    highlights: ["Reparation technique", "Protection du beton", "Format chantier"],
    specifications: spec("Sac de 25 kg", "Reparation et protection du beton"),
  },
  {
    id: "sikagrout-212-scellement",
    brand: "sika",
    name: "SikaGrout-212 Scellement",
    category: "Specialists",
    description: "Mortier de scellement et de calage a base ciment pour applications professionnelles.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: sikaFallback,
    imageNote: unavailablePhoto,
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/1/sikagrout_-212-scellement.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/scellement-et-calage/base-ciment/sikagrout-212-scellement.html",
    highlights: ["Scellement et calage", "Base ciment", "Application professionnelle"],
    specifications: spec("Sac de 25 kg", "Scellement et calage"),
  },
  {
    id: "sika-monotop-1010",
    brand: "sika",
    name: "Sika MonoTop-1010",
    category: "Specialists",
    description: "Passivant et primaire d'adherence pour la protection des armatures et la reparation du beton.",
    unit: "Bidon 1 kg",
    formats: ["1 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hae/hdc/8990288445470/1010-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/f/sika_monotop_-1010.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sika-monotop-1010.html",
    highlights: ["Protection des armatures", "Primaire d'adherence", "Reparation du beton"],
    specifications: spec("Bidon de 1 kg", "Passivation et primaire d'adherence"),
  },
];

export const CATEGORY_ICONS: Record<ProductCategory, ComponentType<{ className?: string }>> = {
  "Tile Adhesive": Sparkles,
  Retail: Boxes,
  Specialists: Wrench,
};
