import type { ComponentType } from "react";
import { Boxes, Droplets, Layers, Paintbrush, Shield, Sparkles, Wrench } from "lucide-react";

export type Brand = "sika" | "terraco" | "lafarge" | "basf" | "decor-boya" | "proseal" | "victo";
export type ProductCategory =
  | "Tile Adhesive"
  | "Retail"
  | "Specialists"
  | "Etancheite"
  | "Enduits & Finition"
  | "Primaires & Accrochage"
  | "Protection"
  | "Isolation"
  | "Mortiers & Enduits"
  | "Adhesifs epoxy"
  | "Primaires & Fixateurs"
  | "Mastics & Collage"
  | "Joints & Waterstop";

export type Product = {
  id: string;
  brand: Brand;
  name: string;
  category: ProductCategory;
  description: string;
  unit: string;
  formats: string[];
  colors?: string[];
  image: string;
  imageNote?: string;
  technicalSheet: string;
  sourceUrl: string;
  highlights: string[];
  specifications: { label: string; value: string }[];
  badge?: string;
  featured?: boolean;
};

export type BrandProfile = {
  name: string;
  color: string;
  accent: string;
  dark: string;
  tagline: string;
  description: string;
  mood: string;
  heroImage: string;
  icon: ComponentType<{ className?: string }>;
};

export const BRANDS: Record<Brand, BrandProfile> = {
  sika: {
    name: "Sika",
    color: "#D8282F",
    accent: "#F5B325",
    dark: "#381411",
    tagline: "Building Trust depuis plus d'un siecle.",
    description: "Chimie de construction, etancheite, collage, scellement et protection du beton.",
    mood: "Rouge chantier, jaune signaletique et cartes techniques tres directes.",
    heroImage: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1600&q=80",
    icon: Shield,
  },
  terraco: {
    name: "Terraco",
    color: "#0A35A5",
    accent: "#2F6DFF",
    dark: "#071B5C",
    tagline: "Finitions scandinaves pour facades et interieurs.",
    description: "Enduits decoratifs, facades, ETICS, coatings et solutions de finition eco-responsables.",
    mood: "Bleu technique, lignes franches et presentation corporate.",
    heroImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80",
    icon: Paintbrush,
  },
  lafarge: {
    name: "Lafarge",
    color: "#16A34A",
    accent: "#111111",
    dark: "#0F1F19",
    tagline: "Ciments, betons et granulats pour ouvrages solides.",
    description: "Solutions cimentaires, mortiers et materiaux lourds pour chantiers structurants.",
    mood: "Vert industriel, noir graphique, blocs robustes et donnees lisibles.",
    heroImage: "https://images.unsplash.com/photo-1517089596392-fb9a9033e05b?auto=format&fit=crop&w=1600&q=80",
    icon: Layers,
  },
  basf: {
    name: "BASF",
    color: "#005B45",
    accent: "#A7D129",
    dark: "#06251E",
    tagline: "Solutions chimiques professionnelles pour collage et protection.",
    description: "Adhesifs epoxy, resines et solutions techniques de la gamme Master Builders / BASF.",
    mood: "Vert BASF, lecture technique et donnees chantier tres directes.",
    heroImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1600&q=80",
    icon: Shield,
  },
  "decor-boya": {
    name: "Decor Boya",
    color: "#D22630",
    accent: "#2C9FDB",
    dark: "#27141A",
    tagline: "Primaires et peintures de preparation pour supports propres.",
    description: "Fixateurs et couches d'accrochage Decor Boya pour preparation des murs et facades.",
    mood: "Rouge, bleu et blanc, presentation peinture claire et orientee finition.",
    heroImage: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=1600&q=80",
    icon: Paintbrush,
  },
  proseal: {
    name: "Proseal",
    color: "#1E88E5",
    accent: "#F6D33C",
    dark: "#0B1D2D",
    tagline: "Mastics, silicones et colles pour joints exigeants.",
    description: "Cartouches Proseal / Nascico pour collage, etancheite, pare-brise et finitions.",
    mood: "Bleu technique, jaune signaletique et visuels produits tres lisibles.",
    heroImage: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1600&q=80",
    icon: Wrench,
  },
  victo: {
    name: "Victo",
    color: "#29308F",
    accent: "#ED1C24",
    dark: "#11143F",
    tagline: "Joints, waterstop et solutions d'etancheite chantier.",
    description: "Produits Victo Team pour joints de dilatation, waterstop et accessoires d'isolation.",
    mood: "Bleu industriel, rouge marque et produits techniques en grand format.",
    heroImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1600&q=80",
    icon: Droplets,
  },
};

const spec = (conditionnement: string, usage: string, marque = "Sika") => [
  { label: "Conditionnement", value: conditionnement },
  { label: "Usage principal", value: usage },
  { label: "Marque", value: marque },
];

const terracoProduct = ({
  id,
  name,
  category,
  description,
  unit,
  image,
  sourceUrl,
  technicalSheet = sourceUrl,
  usage,
  colors,
  badge,
}: {
  id: string;
  name: string;
  category: Extract<ProductCategory, "Etancheite" | "Enduits & Finition" | "Primaires & Accrochage" | "Protection">;
  description: string;
  unit: string;
  image: string;
  sourceUrl: string;
  technicalSheet?: string;
  usage: string;
  colors?: string[];
  badge?: string;
}): Product => ({
  id,
  brand: "terraco",
  name,
  category,
  description,
  unit,
  formats: [unit],
  colors,
  image: `/naf.github.io/products/terraco/${image}`,
  technicalSheet,
  sourceUrl,
  highlights: ["Produit Terraco original", usage, "Disponible chez NAF Factory"],
  specifications: spec(unit, usage, "Terraco"),
  badge,
});

const lafargeProduct = ({
  id,
  name,
  category,
  description,
  unit,
  image,
  sourceUrl,
  technicalSheet = sourceUrl,
  usage,
  colors,
}: {
  id: string;
  name: string;
  category: Extract<ProductCategory, "Isolation" | "Mortiers & Enduits" | "Tile Adhesive">;
  description: string;
  unit: string;
  image: string;
  sourceUrl: string;
  technicalSheet?: string;
  usage: string;
  colors?: string[];
}): Product => ({
  id,
  brand: "lafarge",
  name,
  category,
  description,
  unit,
  formats: [unit],
  colors,
  image,
  technicalSheet,
  sourceUrl,
  highlights: ["Solution Lafarge / Holcim", usage, "Disponible chez NAF Factory"],
  specifications: spec(unit, usage, "Lafarge"),
});

const partnerProduct = ({
  id,
  brand,
  name,
  category,
  description,
  unit,
  image,
  sourceUrl,
  technicalSheet = "",
  usage,
  colors,
  badge,
}: {
  id: string;
  brand: Brand;
  name: string;
  category: ProductCategory;
  description: string;
  unit: string;
  image: string;
  sourceUrl: string;
  technicalSheet?: string;
  usage: string;
  colors?: string[];
  badge?: string;
}): Product => ({
  id,
  brand,
  name,
  category,
  description,
  unit,
  formats: [unit],
  colors,
  image,
  technicalSheet,
  sourceUrl,
  highlights: [`Produit ${BRANDS[brand].name} original`, usage, "Disponible chez NAF Factory"],
  specifications: spec(unit, usage, BRANDS[brand].name),
  badge,
});

export const PRODUCTS: Product[] = [
  {
    id: "sikaceram-511",
    brand: "sika",
    name: "SikaCeram-511",
    category: "Tile Adhesive",
    description: "Mortier-colle cimentaire pour la pose de carreaux en interieur et en exterieur.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hfe/hbd/8995587555358/511-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/n/pds-sikaceram-511.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/colles-a-carreaux/sikaceram-511.html",
    highlights: ["Colle carrelage a base ciment", "Application murs et sols", "Usage interieur et exterieur"],
    specifications: spec("Sac de 25 kg", "Pose de carreaux"),
    badge: "Carrelage",
    featured: true,
  },
  {
    id: "sikaceram-522",
    brand: "sika",
    name: "SikaCeram-522",
    category: "Tile Adhesive",
    description: "Mortier-colle ameliore pour carreaux ceramiques, adapte aux travaux de pose exigeants.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/he5/hc8/8995587457054/522-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/7/pds-sikaceram-522.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/colles-a-carreaux/sikaceram-522.html",
    highlights: ["Adherence amelioree", "Application murs et sols", "Pose professionnelle"],
    specifications: spec("Sac de 25 kg", "Pose de carreaux"),
    featured: true,
  },
  {
    id: "sikaceram-255-starflex",
    brand: "sika",
    name: "SikaCeram-255 StarFlex",
    category: "Tile Adhesive",
    description: "Mortier-colle flexible haute performance pour la pose de carrelage sur supports exigeants.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "/naf.github.io/products/sikaceram-255-starflex.webp",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/w/pds-sikaceram-255largetile.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/colles-a-carreaux.html",
    highlights: ["Formule flexible", "Pose technique de carrelage", "Haute performance"],
    specifications: spec("Sac de 25 kg", "Pose flexible de carreaux"),
    badge: "Flexible",
    featured: true,
  },
  {
    id: "sikaceram-510-joint",
    brand: "sika",
    name: "SikaCeram-510 Joint",
    category: "Tile Adhesive",
    description: "Mortier de jointoiement pour carreaux, propose dans une palette de couleurs pour les finitions.",
    unit: "Sac 5 kg",
    formats: ["5 kg"],
    colors: ["Blanc", "Noir", "Gris clair", "Gris fonce", "Creme", "Chocolat", "Sable", "Sahara"],
    image: "https://pim2.sika.com/medias/sys_master/root/h1b/he6/8997459656734/sika-510-joint.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/k/sikaceram-510-joint.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-de-posedecarreaux/mortier-pour-joints/sikaceram-510-joint.html",
    highlights: ["Jointoiement de carreaux", "Finition coloree", "Large choix de teintes"],
    specifications: spec("Sac de 5 kg", "Joints de carrelage"),
  },
  {
    id: "sikawall-10-primer",
    brand: "sika",
    name: "SikaWall-10 Primer",
    category: "Tile Adhesive",
    description: "Primaire d'accrochage pour la preparation des supports avant application des systemes muraux.",
    unit: "Bidon 20 kg",
    formats: ["20 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/h62/h08/8995587325982/Sikawall10primer-3-.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/n/sikawall-10-primer.pdf",
    sourceUrl: "https://dza.sika.com/fr/products/sikawall-10-primer.html",
    highlights: ["Preparation du support", "Primaire d'accrochage", "Application murale"],
    specifications: spec("Bidon de 20 kg", "Primaire pour supports muraux"),
  },
  {
    id: "conservado-naturiales",
    brand: "sika",
    name: "Conservado Naturiales",
    category: "Tile Adhesive",
    description: "Solution de protection pour surfaces minerales, destinee aux travaux de conservation et de finition.",
    unit: "Bidon 10 L",
    formats: ["10 L"],
    image: "/naf.github.io/products/conservado.png",
    technicalSheet: "https://dza.sika.com/content/dam/dms/dz01/c/conservado-naturiales.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/revetements-des-mursetfacades/conservado-naturiales.html",
    highlights: ["Protection des surfaces", "Application de finition", "Conditionnement professionnel"],
    specifications: spec("Bidon de 10 L", "Protection de surfaces minerales"),
  },
  {
    id: "sikatop-130-flex",
    brand: "sika",
    name: "SikaTop-130 Flex",
    category: "Tile Adhesive",
    description: "Mortier d'impermeabilisation flexible bi-composant pour ouvrages et supports cimentaires.",
    unit: "Kit 32 kg",
    formats: ["Sac 24 kg + bidon 8 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hb3/h0f/8995425517598/130-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/5/pds-sikatopa-130flex.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/revetements-d-impermeabilisation-a-base-de-ciment/sikatop-130-flex.html",
    highlights: ["Systeme bi-composant", "Etancheite flexible", "Kit pret a melanger"],
    specifications: spec("Sac de 24 kg + bidon de 8 kg", "Impermeabilisation flexible"),
    featured: true,
  },
  {
    id: "hydrofuge-sika-liquide",
    brand: "sika",
    name: "Hydrofuge Sika Liquide",
    category: "Retail",
    description: "Adjuvant liquide d'impermeabilisation pour mortiers et betons, destine a limiter la penetration d'eau.",
    unit: "Bidon 2 / 5 / 10 kg",
    formats: ["2 kg", "5 kg", "10 kg"],
    image: "/naf.github.io/products/hydrofuge-sika-liquide.jpg",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/0/hydrofuge-sika-liquide.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/adjuvants-d-impermeabilisationpourbeton/hydrofuge-sika-liquide.html",
    highlights: ["Hydrofugation des mortiers", "Reduction de la penetration d'eau", "Trois formats disponibles"],
    specifications: spec("Bidons de 2 kg, 5 kg et 10 kg", "Impermeabilisation de mortiers et betons"),
    featured: true,
  },
  {
    id: "sikalatex-pro",
    brand: "sika",
    name: "SikaLatex Pro",
    category: "Retail",
    description: "Resine d'accrochage et d'amelioration des mortiers pour reprises, chapes et enduits.",
    unit: "Bidon 2 / 5 / 10 kg",
    formats: ["2 kg", "5 kg", "10 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/h37/h1b/8995705946142/LATEX-PRO-Vue-active-1-.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/5/sikalatex-pro.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sikalatex-pro.html",
    highlights: ["Resine d'accrochage", "Ameliore les mortiers", "Trois formats disponibles"],
    specifications: spec("Bidons de 2 kg, 5 kg et 10 kg", "Accrochage et amelioration des mortiers"),
    badge: "Polyvalent",
    featured: true,
  },
  {
    id: "sikalatex-310-rtu",
    brand: "sika",
    name: "SikaLatex-310 RTU",
    category: "Retail",
    description: "Primaire d'adherence pret a l'emploi pour reprises de beton et travaux de reparation.",
    unit: "Bidon 5 kg",
    formats: ["5 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hd8/h49/8995706044446/3d-310-5kg.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/8/pds-sikalatex-310rtu.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sikalatex-310-rtu.html",
    highlights: ["Pret a l'emploi", "Primaire d'adherence", "Reprises de beton"],
    specifications: spec("Bidon de 5 kg", "Primaire d'adherence"),
  },
  {
    id: "sika-plastocrete-160a",
    brand: "sika",
    name: "Sika Plastocrete-160 A",
    category: "Retail",
    description: "Plastifiant pour beton permettant d'ameliorer l'ouvrabilite et la mise en oeuvre.",
    unit: "Bidon 5 kg",
    formats: ["5 kg"],
    image: "/naf.github.io/products/plastocrete-160a.webp",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/v/pds-sika-plastocrete-160a.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/adjuvants-pour-beton/beton-pret-a-l-emploi/plastifiants/sika-plastocrete-160a.html",
    highlights: ["Plastifiant pour beton", "Ameliore l'ouvrabilite", "Mise en oeuvre facilitee"],
    specifications: spec("Bidon de 5 kg", "Plastification du beton"),
  },
  {
    id: "sikaplast-bv-40-plus",
    brand: "sika",
    name: "SikaPlast BV-40 Plus",
    category: "Retail",
    description: "Reducteur d'eau pour beton permettant d'optimiser la maniabilite et les performances du melange.",
    unit: "Bidon 5 kg",
    formats: ["5 kg"],
    image: "/naf.github.io/products/sikaplast-bv40.webp",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/g/sikaplast-bv-40-plus.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/adjuvants-pour-beton/beton-pret-a-l-emploi/reducteurs-d-eau/reducteurs-d-eau/sikaplast-bv-40-plus.html",
    highlights: ["Reducteur d'eau", "Optimise la maniabilite", "Adjuvant pour beton"],
    specifications: spec("Bidon de 5 kg", "Reduction d'eau pour beton"),
  },
  {
    id: "super-sikalite",
    brand: "sika",
    name: "Super Sikalite",
    category: "Retail",
    description: "Poudre d'impermeabilisation pour mortiers, adaptee aux petits travaux et reparations courantes.",
    unit: "Sac 1 kg",
    formats: ["1 kg"],
    image: "/naf.github.io/products/super-sikalite.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/8/super-sikalite.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/poudre-d-impermeabilisationpourmortier/super-sikalite.html",
    highlights: ["Impermeabilisation des mortiers", "Format pratique", "Travaux courants"],
    specifications: spec("Sac de 1 kg", "Impermeabilisation de mortiers"),
  },
  {
    id: "sikafill",
    brand: "sika",
    name: "Sikafill",
    category: "Retail",
    description: "Revetement liquide d'etancheite pour toitures, disponible en blanc et rouge brique.",
    unit: "Bidon 5 / 20 kg",
    formats: ["5 kg", "20 kg"],
    colors: ["Blanc", "Rouge brique"],
    image: "/naf.github.io/products/sikafill.webp",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/v/sikafill.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/etancheite-liquide/toitures/sikafill.html",
    highlights: ["Etancheite liquide", "Application toiture", "Deux couleurs disponibles"],
    specifications: spec("Bidons de 5 kg et 20 kg", "Etancheite liquide de toitures"),
  },
  {
    id: "sikaflex-pro-11-fc",
    brand: "sika",
    name: "Sikaflex Pro-11 FC",
    category: "Retail",
    description: "Mastic-colle elastique polyvalent en cartouche pour collage et jointoiement dans le batiment.",
    unit: "Cartouche",
    formats: ["Cartouche"],
    image: "/naf.github.io/products/sikaflex-pro-11fc.webp",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/c/sikaflex-pro-11-fc.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/traitement-des-joints/joints-de-facades/sikaflex-pro-11-fc.html",
    highlights: ["Mastic-colle polyvalent", "Application en cartouche", "Collage et joints elastiques"],
    specifications: spec("Cartouche", "Collage et jointoiement"),
    badge: "Mastic-colle",
  },
  {
    id: "sikatop-209-reservoir",
    brand: "sika",
    name: "SikaTop-209 Reservoir",
    category: "Specialists",
    description: "Mortier bi-composant d'impermeabilisation pour ouvrages hydrauliques et reservoirs.",
    unit: "Kit 30 kg",
    formats: ["Sac 20 kg + bidon 10 kg"],
    image: "/naf.github.io/products/sikatop-209.jpg",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/m/sikatop-209-reservoir.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/systemes-d-etancheite/revetements-d-impermeabilisation-a-base-de-ciment/sikatop-209-reservoir.html",
    highlights: ["Systeme bi-composant", "Protection des reservoirs", "Impermeabilisation cimentaire"],
    specifications: spec("Sac de 20 kg + bidon de 10 kg", "Impermeabilisation de reservoirs"),
    featured: true,
  },
  {
    id: "sikatop-107-seal",
    brand: "sika",
    name: "SikaTop-107 Seal",
    category: "Specialists",
    description: "Mortier d'impermeabilisation bi-composant pour la protection des ouvrages en beton.",
    unit: "Kit 25 kg",
    formats: ["Sac 20 kg + bidon 5 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/h9e/h4f/8995537092638/107-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/7/pds-sikatop-107sealwp.pdf",
    sourceUrl: "https://dza.sika.com/fr/products/sikatop-107-sealwp.html",
    highlights: ["Kit bi-composant", "Protection du beton", "Impermeabilisation cimentaire"],
    specifications: spec("Sac de 20 kg + bidon de 5 kg", "Impermeabilisation des ouvrages en beton"),
    featured: true,
  },
  {
    id: "sika-monotop-4012",
    brand: "sika",
    name: "Sika MonoTop-4012",
    category: "Specialists",
    description: "Mortier de reparation structurelle du beton pour travaux professionnels.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hf6/h4e/8990283595806/4012-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/j/pds-sika-monotop-4012.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sika-monotop-4012.html",
    highlights: ["Reparation structurelle", "Application professionnelle", "Support beton"],
    specifications: spec("Sac de 25 kg", "Reparation structurelle du beton"),
    featured: true,
  },
  {
    id: "sika-monotop-650",
    brand: "sika",
    name: "Sika MonoTop-650",
    category: "Specialists",
    description: "Mortier de reparation du beton pour remise en etat des surfaces et ouvrages.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "/naf.github.io/products/monotop-650.webp",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/k/sika-monotop-650.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sika-monotop-650.html",
    highlights: ["Mortier de reparation", "Application sur beton", "Conditionnement chantier"],
    specifications: spec("Sac de 25 kg", "Reparation du beton"),
  },
  {
    id: "sika-monotop-sf-126",
    brand: "sika",
    name: "Sika MonoTop SF-126",
    category: "Specialists",
    description: "Mortier technique pour la reparation et la protection des ouvrages en beton.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/h36/h11/8990288904222/sf126-Vue-active-1-.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/0/sika-monotop-sf-126.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sika-monotop-sf-126.html",
    highlights: ["Reparation technique", "Protection du beton", "Format chantier"],
    specifications: spec("Sac de 25 kg", "Reparation et protection du beton"),
  },
  {
    id: "sikagrout-212-scellement",
    brand: "sika",
    name: "SikaGrout-212 Scellement",
    category: "Specialists",
    description: "Mortier de scellement et de calage a base ciment pour applications professionnelles.",
    unit: "Sac 25 kg",
    formats: ["25 kg"],
    image: "/naf.github.io/products/sikagrout-212-local.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/0/sikagrout-212-scellement.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/scellement-et-calage/base-ciment/sikagrout-212-scellement.html",
    highlights: ["Scellement et calage", "Base ciment", "Application professionnelle"],
    specifications: spec("Sac de 25 kg", "Scellement et calage"),
  },
  {
    id: "sika-monotop-1010",
    brand: "sika",
    name: "Sika MonoTop-1010",
    category: "Specialists",
    description: "Passivant et primaire d'adherence pour la protection des armatures et la reparation du beton.",
    unit: "Bidon 1 kg",
    formats: ["1 kg"],
    image: "https://pim2.sika.com/medias/sys_master/root/hae/hdc/8990288445470/1010-Vue-active.png",
    technicalSheet: "https://dza.sika.com/dam/dms/dz01/n/sika-monotop-1010.pdf",
    sourceUrl: "https://dza.sika.com/fr/construction/reparation-du-beton/sika-monotop-1010.html",
    highlights: ["Protection des armatures", "Primaire d'adherence", "Reparation du beton"],
    specifications: spec("Bidon de 1 kg", "Passivation et primaire d'adherence"),
  },
  terracoProduct({
    id: "terraco-ez-skim",
    name: "Enduit Terraco EZ-Skim",
    category: "Enduits & Finition",
    description: "Enduit de lissage Terraco pour obtenir une surface interieure reguliere avant la finition.",
    unit: "Conditionnement sur devis",
    image: "handycoat-ez-skim.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-ez-skim/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2022/12/63123-Handycoat-EZ-Skim.pdf",
    usage: "Lissage des murs interieurs",
  }),
  terracoProduct({
    id: "flexicoat-blanc-20kg",
    name: "Flexicoat Blanc 20 kg",
    category: "Etancheite",
    description: "Revetement flexible Terraco blanc destine a la protection et a l'impermeabilisation des surfaces.",
    unit: "Seau 20 kg",
    image: "flexicoat.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/flexicoat/",
    usage: "Revetement flexible d'etancheite",
    colors: ["Blanc"],
  }),
  terracoProduct({
    id: "flexicoat-blanc-5kg",
    name: "Flexicoat Blanc 5 kg",
    category: "Etancheite",
    description: "Revetement flexible Terraco blanc destine a la protection et a l'impermeabilisation des surfaces.",
    unit: "Seau 5 kg",
    image: "flexicoat.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/flexicoat/",
    usage: "Revetement flexible d'etancheite",
    colors: ["Blanc"],
  }),
  terracoProduct({
    id: "flexicoat-gris-20kg",
    name: "Flexicoat Gris 20 kg",
    category: "Etancheite",
    description: "Revetement flexible Terraco gris destine a la protection et a l'impermeabilisation des surfaces.",
    unit: "Seau 20 kg",
    image: "flexicoat.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/flexicoat/",
    usage: "Revetement flexible d'etancheite",
    colors: ["Gris"],
  }),
  terracoProduct({
    id: "flexicoat-gris-5kg",
    name: "Flexicoat Gris 5 kg",
    category: "Etancheite",
    description: "Revetement flexible Terraco gris destine a la protection et a l'impermeabilisation des surfaces.",
    unit: "Seau 5 kg",
    image: "flexicoat.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/flexicoat/",
    usage: "Revetement flexible d'etancheite",
    colors: ["Gris"],
  }),
  terracoProduct({
    id: "flexicoat-rouge-20kg",
    name: "Flexicoat Rouge 20 kg",
    category: "Etancheite",
    description: "Revetement flexible Terraco rouge destine a la protection et a l'impermeabilisation des surfaces.",
    unit: "Seau 20 kg",
    image: "flexicoat.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/flexicoat/",
    usage: "Revetement flexible d'etancheite",
    colors: ["Rouge"],
  }),
  terracoProduct({
    id: "flexicoat-rouge-5kg",
    name: "Flexicoat Rouge 5 kg",
    category: "Etancheite",
    description: "Revetement flexible Terraco rouge destine a la protection et a l'impermeabilisation des surfaces.",
    unit: "Seau 5 kg",
    image: "flexicoat.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/flexicoat/",
    usage: "Revetement flexible d'etancheite",
    colors: ["Rouge"],
  }),
  terracoProduct({
    id: "handyprime-5kg",
    name: "Handyprime 5 kg",
    category: "Primaires & Accrochage",
    description: "Primaire Terraco pour egaliser la porosite des murs et preparer la surface avant finition.",
    unit: "Seau 5 kg",
    image: "handyprime.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handyprime/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2023/01/HANDYPRIME.pdf",
    usage: "Preparation des supports muraux",
  }),
  terracoProduct({
    id: "handycoat-anti-humidite-25kg",
    name: "Handycoat Anti-Humidite 25 kg",
    category: "Enduits & Finition",
    description: "Enduit Terraco hydrofuge pour le traitement et la finition des supports exposes a l'humidite.",
    unit: "Seau 25 kg",
    image: "handycoat-hydrofuge.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-hydrofuge/",
    usage: "Enduit hydrofuge pour supports humides",
  }),
  terracoProduct({
    id: "handycoat-exterieur-25kg",
    name: "Handycoat Exterieur 25 kg",
    category: "Enduits & Finition",
    description: "Enduit de finition Terraco pret a l'emploi pour les murs et surfaces exterieurs.",
    unit: "Seau 25 kg",
    image: "handycoat-exterieur.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-exterieur/",
    usage: "Finition des murs exterieurs",
  }),
  terracoProduct({
    id: "handycoat-anti-humidite-5kg",
    name: "Handycoat Anti-Humidite 5 kg",
    category: "Enduits & Finition",
    description: "Enduit Terraco hydrofuge pour le traitement et la finition des supports exposes a l'humidite.",
    unit: "Seau 5 kg",
    image: "handycoat-hydrofuge.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-hydrofuge/",
    usage: "Enduit hydrofuge pour supports humides",
  }),
  terracoProduct({
    id: "handycoat-enduit-ez-joint",
    name: "Handycoat Enduit EZ-Joint",
    category: "Enduits & Finition",
    description: "Enduit Terraco pret a l'emploi pour les joints interieurs et les finitions de plaques.",
    unit: "Conditionnement sur devis",
    image: "handycoat-ez-joint.png",
    sourceUrl: "https://www.terraco.com/products/handycoat-ez-joint/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2022/12/Handycoat-EZ-joint_compressed-1-1.pdf",
    usage: "Traitement des joints interieurs",
  }),
  terracoProduct({
    id: "handycoat-enduit-ez-joint-5kg",
    name: "Handycoat Enduit EZ-Joint 5 kg",
    category: "Enduits & Finition",
    description: "Enduit Terraco pret a l'emploi pour les joints interieurs et les finitions de plaques.",
    unit: "Seau 5 kg",
    image: "handycoat-ez-joint.png",
    sourceUrl: "https://www.terraco.com/products/handycoat-ez-joint/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2022/12/Handycoat-EZ-joint_compressed-1-1.pdf",
    usage: "Traitement des joints interieurs",
  }),
  terracoProduct({
    id: "handycoat-enduit-rebouchage",
    name: "Handycoat Enduit de Rebouchage",
    category: "Enduits & Finition",
    description: "Enduit Terraco pour combler les irregularites et preparer les surfaces avant finition.",
    unit: "Conditionnement sur devis",
    image: "handycoat-rebouchage.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-rebouchage/",
    usage: "Rebouchage et preparation des murs",
  }),
  terracoProduct({
    id: "handycoat-ez-skim",
    name: "Handycoat EZ-Skim",
    category: "Enduits & Finition",
    description: "Enduit Terraco pret a l'emploi pour le lissage rapide des surfaces interieures.",
    unit: "Conditionnement sur devis",
    image: "handycoat-ez-skim.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-ez-skim/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2022/12/63123-Handycoat-EZ-Skim.pdf",
    usage: "Lissage rapide des murs interieurs",
  }),
  terracoProduct({
    id: "handycoat-finition",
    name: "Handycoat Finition",
    category: "Enduits & Finition",
    description: "Enduit Terraco de finition lisse pour preparer les supports interieurs avant decoration.",
    unit: "Conditionnement sur devis",
    image: "handycoat-finition.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-finition/",
    usage: "Finition lisse des murs interieurs",
  }),
  terracoProduct({
    id: "handycoat-interieur-5kg",
    name: "Handycoat Interieur 5 kg",
    category: "Enduits & Finition",
    description: "Enduit Terraco pret a l'emploi pour la preparation et la finition des surfaces interieures.",
    unit: "Seau 5 kg",
    image: "handycoat-interieur.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-interieur/",
    usage: "Preparation des murs interieurs",
  }),
  terracoProduct({
    id: "handycoat-interieur-25kg",
    name: "Handycoat Interieur 25 kg",
    category: "Enduits & Finition",
    description: "Enduit Terraco pret a l'emploi pour la preparation et la finition des surfaces interieures.",
    unit: "Seau 25 kg",
    image: "handycoat-interieur.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handycoat-interieur/",
    usage: "Preparation des murs interieurs",
  }),
  terracoProduct({
    id: "handyprime-20kg",
    name: "Handyprime 20 kg",
    category: "Primaires & Accrochage",
    description: "Primaire Terraco pour egaliser la porosite des murs et preparer la surface avant finition.",
    unit: "Seau 20 kg",
    image: "handyprime.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/handyprime/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2023/01/HANDYPRIME.pdf",
    usage: "Preparation des supports muraux",
  }),
  terracoProduct({
    id: "terrabond-cp-20kg",
    name: "Terrabond CP 20 kg",
    category: "Primaires & Accrochage",
    description: "Primaire d'adherence Terraco pour ameliorer l'accrochage sur les supports avant application.",
    unit: "Seau 20 kg",
    image: "terrabond-cp.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/terrabond-cp/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2023/01/68126-Terrabond-CP.pdf",
    usage: "Primaire d'adherence",
  }),
  terracoProduct({
    id: "terrabond-cp-5kg",
    name: "Terrabond CP 5 kg",
    category: "Primaires & Accrochage",
    description: "Primaire d'adherence Terraco pour ameliorer l'accrochage sur les supports avant application.",
    unit: "Seau 5 kg",
    image: "terrabond-cp.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/terrabond-cp/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2023/01/68126-Terrabond-CP.pdf",
    usage: "Primaire d'adherence",
  }),
  terracoProduct({
    id: "terracrete-20kg",
    name: "Terracrete 20 kg",
    category: "Etancheite",
    description: "Systeme Terraco d'impermeabilisation bi-composant pour les supports cimentaires.",
    unit: "Kit 20 kg",
    image: "terracrete.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/terracrete/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2023/01/Terracrete.pdf",
    usage: "Impermeabilisation bi-composant",
  }),
  terracoProduct({
    id: "terraseal-h100",
    name: "Terraseal H100",
    category: "Etancheite",
    description: "Systeme Terraco d'impermeabilisation pour la protection des supports exposes a l'eau.",
    unit: "Kit 20 kg",
    image: "terraseal-h100.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/terraseal-h-100/",
    technicalSheet: "https://www.terraco.com/dz-fr/wp-content/uploads/2023/01/Terraseal-H100.pdf",
    usage: "Impermeabilisation des supports",
  }),
  terracoProduct({
    id: "weathercoat-gp",
    name: "Weathercoat GP",
    category: "Etancheite",
    description: "Revetement Terraco impermeabilisant pour facades, formule pour resister aux conditions exterieures.",
    unit: "Seau 20 kg",
    image: "weathercoat-gp.png",
    sourceUrl: "https://www.terraco.com/dz-fr/products/weathercoat-gp/",
    usage: "Protection impermeabilisante des facades",
  }),
  lafargeProduct({
    id: "lafarge-m600",
    name: "AIRIUM Thermofloor M600",
    category: "Isolation",
    description: "Mousse minerale isolante Lafarge AIRIUM produite sur chantier pour l'isolation des planchers.",
    unit: "Solution chantier",
    image: "/naf.github.io/products/lafarge/airium.jpg",
    sourceUrl: "https://www.lafarge.dz/airiumtm-lisolation-autrement",
    technicalSheet: "https://www.lafarge.dz/sites/algeria/files/2022-04/Airium_Thermofloor_M600_fr.pdf",
    usage: "Isolation des planchers",
  }),
  lafargeProduct({
    id: "lafarge-airium",
    name: "AIRIUM",
    category: "Isolation",
    description: "Solution d'isolation minerale Lafarge a base de ciment, produite sur chantier selon l'application.",
    unit: "Solution chantier",
    image: "/naf.github.io/products/lafarge/airium.jpg",
    sourceUrl: "https://www.lafarge.dz/airiumtm-lisolation-autrement",
    technicalSheet: "https://www.lafarge.dz/sites/algeria/files/2022-04/Airium_Thermoroof_fr.pdf",
    usage: "Isolation minerale produite sur chantier",
  }),
  ...[
    ["blanc", "Blanc"],
    ["blanc-casse", "Blanc casse"],
    ["gris-clair", "Gris clair"],
    ["gris-fonce", "Gris fonce"],
    ["beige", "Beige"],
    ["marron-clair", "Marron clair"],
    ["marron-inaya", "Marron Inaya"],
  ].map(([slug, color]) =>
    lafargeProduct({
      id: `monocouche-721-${slug}`,
      name: `Monocouche 721 ${color} 25 kg`,
      category: "Mortiers & Enduits",
      description: `Enduit monocouche Lafarge 721 teinte ${color.toLowerCase()} pour la decoration et l'impermeabilisation des facades.`,
      unit: "Sac 25 kg",
      image: "/naf.github.io/products/lafarge/tectorplast-721.jpg",
      sourceUrl: "https://www.lafarge.dz/tectorplast-enduit-monocouche-blanc-ou-teinte-721",
      technicalSheet: "https://www.lafarge.dz/sites/algeria/files/documents/mortier_fiche_technique_721.pdf",
      usage: "Decoration et impermeabilisation des facades",
      colors: [color],
    }),
  ),
  lafargeProduct({
    id: "tectorceram-321-c2",
    name: "Mortier Colle Blanc TectorCeram 321 C2",
    category: "Tile Adhesive",
    description: "Mortier-colle blanc extreme C2 TE Lafarge pour carreaux, ceramique, pierre naturelle et granite.",
    unit: "Sac 25 kg",
    image: "/naf.github.io/products/lafarge/tectorceram-321.jpg",
    sourceUrl: "https://www.lafarge.dz/tectorceram-mortier-colle-blanc-extreme-c2-te-max-321",
    technicalSheet: "https://www.lafarge.dz/sites/algeria/files/2022-04/tectorceram_321_fr.pdf",
    usage: "Pose haute performance de carrelage",
  }),
  lafargeProduct({
    id: "tectorceram-311-c1",
    name: "Mortier Colle Blanc TectorCeram 311 C1",
    category: "Tile Adhesive",
    description: "Mortier-colle superieur blanc C1T Lafarge pour la pose professionnelle de carrelage.",
    unit: "Sac 25 kg",
    image: "/naf.github.io/products/lafarge/tectorceram-311.jpg",
    sourceUrl: "https://www.lafarge.dz/tectorceram-mortier-colle-superieur-blanc-c1t-extra-311",
    technicalSheet: "https://www.lafarge.dz/sites/algeria/files/2022-04/tectorceram_311_fr.pdf",
    usage: "Pose professionnelle de carrelage",
  }),
  lafargeProduct({
    id: "tectorceram-301-c0",
    name: "Mortier Colle Blanc TectorCeram 301 C0",
    category: "Tile Adhesive",
    description: "Mortier-colle blanc standard Lafarge pour la pose courante de carreaux.",
    unit: "Sac 25 kg",
    image: "/naf.github.io/products/lafarge/tectorceram-301.jpg",
    sourceUrl: "https://www.lafarge.dz/tectorceram-mortier-colle-blanc-standard-eco-301",
    technicalSheet: "https://www.lafarge.dz/sites/algeria/files/2022-04/tectorceram_301_fr.pdf",
    usage: "Pose standard de carreaux",
  }),
  lafargeProduct({
    id: "tectorceram-300-c0",
    name: "Mortier Colle Blanc TectorCeram 300 C0",
    category: "Tile Adhesive",
    description: "Mortier-colle Lafarge ECO 300 pour la pose courante de carreaux sur supports adaptes.",
    unit: "Sac 25 kg",
    image: "/naf.github.io/products/lafarge/tectorceram-300.jpg",
    sourceUrl: "https://www.lafarge.dz/tectorceram-mortier-colle-gris-standard-eco-300",
    technicalSheet: "https://www.lafarge.dz/sites/algeria/files/2022-04/tectorceram_300_fr.pdf",
    usage: "Pose economique de carreaux",
  }),
  lafargeProduct({
    id: "tectorplast-111",
    name: "Mortier de Crepissage 111 TectorPlast 25 kg",
    category: "Mortiers & Enduits",
    description: "Mortier de crepissage blanc Lafarge TectorPlast 111 pour travaux interieurs et exterieurs.",
    unit: "Sac 25 kg",
    image: "/naf.github.io/products/lafarge/tectorplast-110-111.jpg",
    sourceUrl: "https://www.lafarge.dz/tectorplast-mortier-de-crepissage-blanc-111",
    technicalSheet: "https://www.lafarge.dz/sites/algeria/files/2022-04/tectorplast_111_fr_0.pdf",
    usage: "Crepissage blanc interieur et exterieur",
  }),
  lafargeProduct({
    id: "tectorplast-110",
    name: "Mortier de Crepissage 110 TectorPlast 25 kg",
    category: "Mortiers & Enduits",
    description: "Mortier de crepissage gris Lafarge TectorPlast 110 pour travaux interieurs et exterieurs.",
    unit: "Sac 25 kg",
    image: "/naf.github.io/products/lafarge/tectorplast-110-111.jpg",
    sourceUrl: "https://www.lafarge.dz/tectorplast-110-mortier-de-crepissage-gris",
    technicalSheet: "https://www.lafarge.dz/sites/algeria/files/2022-04/tectorplast_110_fr.pdf",
    usage: "Crepissage gris interieur et exterieur",
  }),
  partnerProduct({
    id: "basf-masterbrace-adh2200-1kg",
    brand: "basf",
    name: "MASTER BRACE ADH 2200 1 KG",
    category: "Adhesifs epoxy",
    description: "Adhesif epoxy bi-composant MasterBrace ADH 2200 pour collage et ancrage technique.",
    unit: "Kit 1 kg",
    image: "/naf.github.io/products/basf/masterbrace-adh2200.jpg",
    sourceUrl: "https://www.bullshardware.com/products/master-brace-adh-22007-5kg",
    usage: "Collage epoxy structurel",
  }),
  partnerProduct({
    id: "basf-masterbrace-adh2200-5kg",
    brand: "basf",
    name: "MASTER BRACE ADH 2200 5 KG",
    category: "Adhesifs epoxy",
    description: "Kit epoxy MasterBrace ADH 2200 en format chantier pour collages resistants.",
    unit: "Kit 5 kg",
    image: "/naf.github.io/products/basf/masterbrace-adh2200.jpg",
    sourceUrl: "https://www.bullshardware.com/products/master-brace-adh-22007-5kg",
    usage: "Collage epoxy structurel",
  }),
  ...[
    ["bleu", "BLEU"],
    ["grey", "GREY"],
    ["white", "WHITE"],
  ].map(([slug, color]) =>
    partnerProduct({
      id: `basf-masterbrace-180-${slug}`,
      brand: "basf",
      name: `MASTER BRACE 180 ${color} KIT 5 KG`,
      category: "Adhesifs epoxy",
      description: `Kit MasterBrace 180 ${color.toLowerCase()} 5 kg pour revetement et protection epoxy.`,
      unit: "Kit 5 kg",
      image: "/naf.github.io/products/basf/masterbrace-180.jpg",
      sourceUrl: "https://www.psbalgerie.com/product-page/masterprotect-180-peinture-epoxy-imperm%C3%A9abilisante-5kg",
      usage: "Protection epoxy impermeabilisante",
      colors: [color],
    }),
  ),
  partnerProduct({
    id: "basf-adh1414-1kg",
    brand: "basf",
    name: "BASF ADH 1414 1 KG",
    category: "Adhesifs epoxy",
    description: "Adhesif epoxy ADH 1414 en kit compact pour reparations et collages techniques.",
    unit: "Kit 1 kg",
    image: "/naf.github.io/products/basf/adh1414.jpg",
    sourceUrl: "https://chemicalandapplication.com/product/master-brace-1414/",
    usage: "Collage et reparation epoxy",
  }),
  partnerProduct({
    id: "basf-adh1414-3kg",
    brand: "basf",
    name: "BASF ADH 1414 3KG",
    category: "Adhesifs epoxy",
    description: "Adhesif epoxy ADH 1414 en format 3 kg pour travaux de collage et reparation.",
    unit: "Kit 3 kg",
    image: "/naf.github.io/products/basf/adh1414.jpg",
    sourceUrl: "https://chemicalandapplication.com/product/master-brace-1414/",
    usage: "Collage et reparation epoxy",
  }),
  ...[
    ["jaune", "FIXATEUR JAUNE 20KG", "Jaune"],
    ["rouge", "FIXATEUR ROUGE 20KG", "Rouge"],
  ].map(([slug, name, color]) =>
    partnerProduct({
      id: `decor-boya-fixateur-${slug}`,
      brand: "decor-boya",
      name,
      category: "Primaires & Fixateurs",
      description: `Fixateur Decor Boya / Deko Kontak ${color.toLowerCase()} pour preparation et accrochage des supports.`,
      unit: "Seau 20 kg",
      image: "/naf.github.io/products/decor-boya/deko-kontak.jpg",
      sourceUrl: "https://www.decorboya.org/",
      usage: "Primaire d'accrochage avant finition",
      colors: [color],
    }),
  ),
  partnerProduct({
    id: "proseal-naci-anchor",
    brand: "proseal",
    name: "ANCRAGE CHIMIQUE NACI-ANCHOR",
    category: "Adhesifs epoxy",
    description: "Resine de scellement chimique NACI-ANCHOR Proseal pour ancrages haute performance.",
    unit: "Cartouche 280 ml",
    image: "/naf.github.io/products/proseal/naci-anchor.avif",
    sourceUrl: "https://dekkal-quincaillerie.dz/fr/produit/resine-dancrage-chimique-naci-anchor-pro-proseal/",
    usage: "Scellement chimique et ancrage",
  }),
  partnerProduct({
    id: "proseal-carbosil-noir",
    brand: "proseal",
    name: "CARBOSIL NOIR 310ML",
    category: "Mastics & Collage",
    description: "Colle pare-brise Proseal Carbosil noire pour vitrage et carrosserie.",
    unit: "Cartouche 310 ml",
    image: "/naf.github.io/products/proseal/carbosil.jpg",
    sourceUrl: "https://bricaillerie.com/",
    usage: "Collage pare-brise et vitrages",
    colors: ["Noir"],
  }),
  partnerProduct({
    id: "proseal-motorseal",
    brand: "proseal",
    name: "MOTORSEAL 300ML",
    category: "Mastics & Collage",
    description: "Mastic Proseal Motorseal pour joints moteur, etancheite mecanique et applications techniques.",
    unit: "Cartouche 300 ml",
    image: "/naf.github.io/products/proseal/motorseal.jpg",
    sourceUrl: "https://www.psbalgerie.com/",
    usage: "Etancheite mecanique",
  }),
  partnerProduct({
    id: "proseal-crystaseal",
    brand: "proseal",
    name: "CRYSTASEAL 300ML",
    category: "Mastics & Collage",
    description: "Colle elastique transparente Proseal Crystaseal pour collage et etancheite discrete.",
    unit: "Cartouche 300 ml",
    image: "/naf.github.io/products/proseal/crystaseal.jpg",
    sourceUrl: "https://bricaillerie.com/",
    usage: "Collage elastique transparent",
  }),
  partnerProduct({
    id: "proseal-nacisil-deco-montage",
    brand: "proseal",
    name: "NACSIL DECO MONTAGE 300ML",
    category: "Mastics & Collage",
    description: "Colle acrylique Nacisil Deco & Montage pour fixation de decoration et finitions interieures.",
    unit: "Cartouche 300 ml",
    image: "/naf.github.io/products/proseal/nacisil-deco-montage.jpg",
    sourceUrl: "https://bricaillerie.com/",
    usage: "Collage decoration et montage",
  }),
  ...[
    ["blanc", "NACSIL MULTI-USAGE BLANC 300ML", "Blanc"],
    ["transparent", "NACSIL MULTI-USAGE TRANSPARENT 300ML", "Transparent"],
  ].map(([slug, name, color]) =>
    partnerProduct({
      id: `proseal-nacisil-multi-${slug}`,
      brand: "proseal",
      name,
      category: "Mastics & Collage",
      description: `Silicone Proseal Nacisil multi-usage ${color.toLowerCase()} pour joints d'etancheite et collage courant.`,
      unit: "Cartouche 300 ml",
      image: "/naf.github.io/products/proseal/nacisil-multi-usage.jpg",
      sourceUrl: "https://bricaillerie.com/",
      usage: "Joints d'etancheite multi-usage",
      colors: [color],
    }),
  ),
  ...[
    ["gris", "POLYFLEX PU 40 GRIS 300ML", "Gris"],
    ["noir", "POLYFLEX PU 40 NOIR 300ML", "Noir"],
    ["blanc", "POLYFLEX PU40 BLANC 300ML", "Blanc"],
    ["beige", "POLYFLEX PU40 BEIGE 300ML", "Beige"],
  ].map(([slug, name, color]) =>
    partnerProduct({
      id: `proseal-polyflex-pu40-${slug}`,
      brand: "proseal",
      name,
      category: "Mastics & Collage",
      description: `Colle polyurethane Proseal Polyflex PU40 ${color.toLowerCase()} pour collage souple et etancheite.`,
      unit: "Cartouche 300 ml",
      image: "/naf.github.io/products/proseal/polyflex-pu40.jpg",
      sourceUrl: "https://www.vcmbat-alger.dz/colle-nascico-polyflex-pu40-proseal.html",
      usage: "Collage polyurethane souple",
      colors: [color],
    }),
  ),
  partnerProduct({
    id: "proseal-extraseal-high-tack-blanc",
    brand: "proseal",
    name: "EXTRASEAL HIGH TACK BLANC 280ML",
    category: "Mastics & Collage",
    description: "Colle mastic Proseal Extraseal High Tack blanche pour collage puissant et maintien immediat.",
    unit: "Cartouche 280 ml",
    image: "/naf.github.io/products/proseal/extraseal-high-tack.jpg",
    sourceUrl: "https://bricaillerie.com/",
    usage: "Collage high tack",
    colors: ["Blanc"],
  }),
  partnerProduct({
    id: "proseal-silicon-fast-bond08",
    brand: "proseal",
    name: "SILICON FAST BOND-08 310ML",
    category: "Mastics & Collage",
    description: "Silicone colle Proseal Fast Bond-08 pour collage et etancheite rapide en cartouche.",
    unit: "Cartouche 310 ml",
    image: "/naf.github.io/products/proseal/silicon-fast-bond08.jpg",
    sourceUrl: "https://www.ouedkniss.com/",
    usage: "Collage silicone rapide",
  }),
  ...[
    ["blanc", "ACRYSEAL BLANC 500G", "Blanc"],
    ["gris", "ACRYSEAL GRIS 500G", "Gris"],
    ["marron", "ACRYSEAL MARRON 500G", "Marron"],
  ].map(([slug, name, color]) =>
    partnerProduct({
      id: `proseal-acryseal-${slug}`,
      brand: "proseal",
      name,
      category: "Mastics & Collage",
      description: `Mastic acrylique siliconise Proseal Acryseal ${color.toLowerCase()} pour joints et fissures.`,
      unit: "Pot 500 g",
      image: "/naf.github.io/products/proseal/acryseal.jpg",
      sourceUrl: "https://bricaillerie.com/",
      usage: "Rebouchage et joint acrylique",
      colors: [color],
    }),
  ),
  ...[
    ["200-10", "JOINT WATER STOP 200MM /10M", "200 mm / 10 m"],
    ["200-15", "JOINT WATER STOP 200MM /15M", "200 mm / 15 m"],
    ["200-20", "JOINT WATER STOP 200MM /20M", "200 mm / 20 m"],
    ["250-10", "JOINT WATER STOP 250MM /10M", "250 mm / 10 m"],
    ["250-15", "JOINT WATER STOP 250MM /15M", "250 mm / 15 m"],
    ["300-15", "JOINT WATER STOP 300 M/M15 M", "300 mm / 15 m"],
    ["300-25", "JOINT WATER STOP 300MM/25M", "300 mm / 25 m"],
  ].map(([slug, name, unit]) =>
    partnerProduct({
      id: `victo-waterstop-${slug}`,
      brand: "victo",
      name,
      category: "Joints & Waterstop",
      description: `Joint waterstop Victo ${unit} pour etancheite des reprises et joints beton.`,
      unit,
      image: "/naf.github.io/products/victo/waterstop-plat.png",
      sourceUrl: "https://victoteam.com/product/water-stop-plat/",
      usage: "Etancheite des joints beton",
    }),
  ),
  partnerProduct({
    id: "victo-tapis-foam-ep8-blanc",
    brand: "victo",
    name: "TAPIS FOAM EP-8 BLANC",
    category: "Joints & Waterstop",
    description: "Tapis foam Victo EP-8 blanc pour isolation et traitement des joints.",
    unit: "EP-8 blanc",
    image: "/naf.github.io/products/victo/joint-dilatation-15cm.webp",
    sourceUrl: "https://victoteam.com/product/joint-dilatation-15cm/",
    usage: "Isolation et joint de dilatation",
    colors: ["Blanc"],
  }),
  partnerProduct({
    id: "victo-tapis-foam-ep6-gris",
    brand: "victo",
    name: "TAPIS FOAM EP-6 GRIS",
    category: "Joints & Waterstop",
    description: "Tapis foam Victo EP-6 gris pour isolation et traitement des joints.",
    unit: "EP-6 gris",
    image: "/naf.github.io/products/victo/joint-de-sol.webp",
    sourceUrl: "https://victoteam.com/product/joint-de-sol/",
    usage: "Isolation et joint de sol",
    colors: ["Gris"],
  }),
];

export const CATEGORY_ICONS: Record<ProductCategory, ComponentType<{ className?: string }>> = {
  "Tile Adhesive": Sparkles,
  Retail: Boxes,
  Specialists: Wrench,
  Etancheite: Droplets,
  "Enduits & Finition": Paintbrush,
  "Primaires & Accrochage": Layers,
  Protection: Shield,
  Isolation: Sparkles,
  "Mortiers & Enduits": Layers,
  "Adhesifs epoxy": Shield,
  "Primaires & Fixateurs": Paintbrush,
  "Mastics & Collage": Wrench,
  "Joints & Waterstop": Droplets,
};
